name: golangci-lint
on:
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    container: golang:1.22.2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setug-go@v5
        with:
          go-version: 'latest'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.5.0
