name: Test with multichecker
on:
  pull_request:

jobs:
  test:
    name: multichecker
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run
        run: go run ./cmd/staticlint/multichecker.go ./...
